name: SampleApp
options:
  bundleIdPrefix: com.sample
  deploymentTarget:
    iOS: "15.0"
  xcodeVersion: "16.0"
settings:
  base:
    SWIFT_VERSION: "5.9"
packages:
  BottomSheet:
    path: ../BottomSheet
targets:
  SampleApp:
    type: application
    platform: iOS
    sources:
      - path: Sources
    dependencies:
      - package: BottomSheet
    settings:
      base:
        INFOPLIST_GENERATION_MODE: GeneratedFile
        PRODUCT_BUNDLE_IDENTIFIER: com.sample.bottomsheet-sample
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait"
